[server]
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = false 